### ISSUE TITLE
首先庆祝作者回来了！我有看到了一点点的小问题。

### ISSUE THREAD

**Issue by Jack6811** [dylech30th/Pixeval#101]
首先庆祝作者回来了！
如果作者家中还是有事情的话，就先忙吧，我的issue并不是那重要。

还是老问题，低分辨率兼容。
我的计算机在192.*1080分辨率下打开软件会直接超出显示范围
<img width="960" alt="微信图片_20200927223320" src="https://user-images.githubusercontent.com/57797431/94367457-8907e580-0111-11eb-91e9-8119448475f8.png">
如果全屏的话会造成输入框被强制缩小甚至重叠，包括但不限于设置界面
<img width="960" alt="微信图片_20200927223535" src="https://user-images.githubusercontent.com/57797431/94367510-c8cecd00-0111-11eb-8392-36a3face3315.png">
如果有办法解决的话作者就解决了吧

**Comment by Rinacm** [comment]
啊这个是分段修复的，上次更新是因为没法登录所导致的紧急更新，实际上部分bug并没有完全修复，只是因为没法登录所以紧急更新了一次，issue里面的bug我在一个一个针对修复，修复bug之后就会更新更加完善的版本

**Comment by Jack6811** [comment]
好的，加油

**Comment by Jack6811** [comment]
还有就是希望作者可以支持Home/End按键的支持，以便可以快速回到顶部或底部

**Comment by Rinacm** [comment]
好的，下个版本就会放出

**Comment by tiannailingyin** [comment]
最近我加载不出图片了，提示当前设置下无法找到任何作品，直连也开了，是我网络的问题还是软件出问题了呢

**Comment by Jack6811** [comment]
> 最近我加载不出图片了，提示当前设置下无法找到任何作品，直连也开了，是我网络的问题还是软件出问题了呢

试试安装最新版，如果不行试试删除%AppData%/../Local/pixeval 文件夹。

**Comment by dylech30th** [comment]
#108

**Comment by Jack6811** [comment]
哈希效验失败，自动更新应按没问题吧？我试了两次，都一样，我的网络环境应该没问题。
再一个有就是个人网站的下载现在为2.2.4非最新版

**Comment by dylech30th** [comment]
我脑瘫忘了上传文件，已经上传了
