### ISSUE TITLE
关于一个一直以来都有的问题

### ISSUE THREAD

**Issue by Taoyao942333** [dylech30th/Pixeval#104]
作者您好，pixeval是我目前为止用的最好的一个软件，但我换了新电脑之后把它下下来好几天了，页面没有任何的显示，不知道是什么原因，没有任何的图片和文字的显示

**Comment by henryEX** [comment]
你开启了直连选项吗，直连选项默认是关闭的

**Comment by dylech30th** [comment]
确保在设置里打开了直连
