### ISSUE TITLE
希望可以自定义图片服务器地址

### ISSUE THREAD

**Issue by Misaka-L** [dylech30th/Pixeval#105]
由于一些众所周知的原因，i.pximg.net 要不就是打不开要不就是慢的要死
但是我们可以通过建镜像站来解决，希望作者可以考虑一下添加自定义图片服务器地址的功能
(不要问为什么不建 Pixiv 的镜像站，太折磨人了，大半天都弄不好)

**Comment by Rinacm** [comment]
emm这个....自定义图片服务器地址的话，具体的api要怎么解决，用占位符吗

**Comment by Misaka-L** [comment]
> emm这个....自定义图片服务器地址的话，具体的api要怎么解决，用占位符吗

直接在返回信息获得到图片地址里的 "i.pximg.net" 替换成 "镜像站" 地址就可以使用镜像站加载图片了。
比如说我自己建的图片服务器镜像站地址是 nginx.misakal.xyz，那么
```C#
string imageUri = "https:\/\/i.pximg.net\/img-original\/img\/2018\/03\/31\/01\/10\/08\/67994735_p0.png"; // 从 Api 获取的图片地址
imageUri.Replace("i.pximg.net", "nginx.misakal.xyz"); // 替换地址
```

**Comment by Misaka-L** [comment]
附几个镜像站地址 (别用我那个，小水管带一个就够难受了)
- [pixiv.cat](pixiv.cat)
调用方法 https://pixiv.cat/ + 原地址删除 "https://i.pximg.net/"
- [pixiv.re](pixiv.re)
调用方法 https://pixiv.re/ + 原地址删除 "https://i.pximg.net/"
- [pixiv.moe](https://pixiv.moe/)
调用方法 https://api.kotori.love/pixiv/image/i.pximg.net/  + 原地址删除 "https://i.pximg.net/"

**Comment by Misaka-L** [comment]
> emm这个....自定义图片服务器地址的话，具体的api要怎么解决，用占位符吗

我自己尝试实现了一下，这里是 Pull request 地址: https://github.com/Rinacm/Pixeval/pull/107

**Comment by dylech30th** [comment]
新版本已经添加，马上推送

**Comment by dylech30th** [comment]
抱歉没有看到之前的pr，新版本已经加入了，马上推送
