### ISSUE TITLE
总是提示无法根据当前设置找到任何作品

### ISSUE THREAD

**Issue by tenjouin** [dylech30th/Pixeval#108]
总是提示无法根据当前设置找到任何作品，开启直连也没用

**Comment by dylech30th** [comment]
p站api更换的小bug，今天修复

**Comment by maxcmonster** [comment]
从昨天开始一样的问题，提示无法根据当前设置找到任何作品，开启直连也没用；
今天还是这样 ><

**Comment by dylech30th** [comment]
> 从昨天开始一样的问题，提示无法根据当前设置找到任何作品，开启直连也没用；
> 今天还是这样 ><

我知道，我昨天在忙blog的事情，今天把blog忙完就修了

**Comment by qbs233** [comment]
辛苦了 作者 哈哈这几天所有的p站软件都不行了

**Comment by dylech30th** [comment]
小毛病而已

**Comment by maxcmonster** [comment]
搞定啦，撒花~

**Comment by Misaka-L** [comment]
> 搞定啦，撒花~

那 Close Issue 啊

**Comment by maxcmonster** [comment]
> > 搞定啦，撒花~
> 
> 那 Close Issue 啊

啊，不是我开的话题呀 ><
