### ISSUE TITLE
无法登入

### ISSUE THREAD

**Issue by J-Lent** [dylech30th/Pixeval#110]
![000](https://user-images.githubusercontent.com/70250757/95672224-991fca80-0bd1-11eb-9ed9-c878c0bc7371.png)

 如图，就是卡死在这个登入界面，无论输入的账户正确与否，就算输入两个数字它也没反应。

win10，已安装.NET Core 3.1 Runtim，  Visual C++ Redistributable 2019

（补，卡住一段时间后会显示密码错误，然鹅我输入正确密码也告诉我密码错误）

（补：debug文档 重复 ：   [1011/144932.399:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -207    ）

**Comment by Summpot** [comment]
版本如何？

**Comment by J-Lent** [comment]
当然是最新的啊...
但是自从这个软件变成粉红色（ ‵▽′)ψ 开始，我就没打开成功打开过...都是这个问题。
那时候原版（蓝色exe）还能用，我过来看了下发现作者因故断更，就以为是版本bug也就没来反馈，
但现在原版（蓝色）的也没法使用了，作者也喜归，粉红色的新版我试了几个版本的都没法用，就来反馈下。
![QQ图片20201012220454](https://user-images.githubusercontent.com/70250757/95755509-15500600-0cd7-11eb-9528-c732c6afd975.png)

虽然原版的小蓝一堆问题我下图都是一张一张点的，但，但...TAT

**Comment by dylech30th** [comment]
看你这debug信息是握手失败了？那应该是webapi登录的问题，我最近已经在重构了，而且你去release里找一下没有webapi的版本看能不能打得开，要是没有webapi的版本也打不开那就可能是你电脑的问题了
