### ISSUE TITLE
设置中部分项显示不全

### ISSUE THREAD

**Issue by Poker-sang** [dylech30th/Pixeval#111]
![@{ 6LP3A9@$)E{IM9GS4IB0](https://user-images.githubusercontent.com/62325494/96902728-780b8380-14c7-11eb-8ec6-eaa504487c8a.png)

**Comment by Misaka-L** [comment]
我提了个 PR 解决这个问题，但是作者现在都没通过....

**Comment by dylech30th** [comment]
> 我提了个 PR 解决这个问题，但是作者现在都没通过....

特殊原因，我现在每天要去治病，晚上回来才有时间，但是时间很少，我看看明天能不能review一下

**Comment by Misaka-L** [comment]
> > 我提了个 PR 解决这个问题，但是作者现在都没通过....
> 
> 特殊原因，我现在每天要去治病，晚上回来才有时间，但是时间很少，我看看明天能不能review一下

秒回？？？？？？

**Comment by dylech30th** [comment]
刚好在用电脑..
