### ISSUE TITLE
“下载作者作品时使用单独文件夹“不可用

### ISSUE THREAD

**Issue by sophie-desu** [dylech30th/Pixeval#117]
在作者主页下载全部作品时会直接把作品下载到选择的”作品下载位置“文件夹中
以前会在”作品下载位置“文件夹中创建新的文件夹

**Comment by yyzzz12345** [comment]
选中“下载作者作品时使用单独文件夹”后，从作者主页下载作品仍然无法自动创建单独文件夹。

**Comment by dylech30th** [comment]
https://github.com/dylech30th/Pixeval/releases/tag/3.1.1
使用了包含宏的自定义下载路径
