### ISSUE TITLE
更新报错

### ISSUE THREAD

**Issue by J-Lent** [dylech30th/Pixeval#118]
...我就是那个上一次死在入口的人

是准备隔段时间就来看一下我能不能兼容这款软件的

现在出现了新的问题，说不定是我没法登入的原因之一呢。

情况如下，

解压，找到红色图标的exe，双击

然后就弹出了有新更新可用的提示，

点击， 然后如图报错

![20201110154359](https://user-images.githubusercontent.com/70250757/98645887-8e418c80-236d-11eb-8560-4a1b90863744.jpg)

(╬▔皿▔)凸

上报是也

**Comment by dylech30th** [comment]
fixed
