### ISSUE TITLE
更新报错且无法打开软件(win10

### ISSUE THREAD

**Issue by Rillbeye** [dylech30th/Pixeval#120]
如图，想知道解决方法![QQ图片20201113230315](https://user-images.githubusercontent.com/74300920/99086389-6e77c600-2604-11eb-8109-d36d8db9a3af.png)

**Comment by dylech30th** [comment]
fixed

**Comment by Rillbeye** [comment]
确实更新不报错了，但是启动软件后连登录界面也不跳，过了一会就在后台自动关闭了，求大大解决

**Comment by Rillbeye** [comment]
更新确实修好了可是还是打不开软件，双击应用什么反应都没有，必要的组件也都下了，之前从来没出现过这种情况，请问dalao如何解决
