### ISSUE TITLE
双击应用什么反应都没有，必要的组件也都下了，之前从来没出现过这种情况，请问dalao如何解决(win10

### ISSUE THREAD

**Issue by Rillbeye** [dylech30th/Pixeval#121]
如题

**Comment by qbs233** [comment]
我重启电脑解决

**Comment by Rillbeye** [comment]
重启了还是没用啊，dalao咋办啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qbs233"<notifications@github.com&gt;; 
发送时间: 2020年11月16日(星期一) 晚上6:17
收件人: "dylech30th/Pixeval"<Pixeval@noreply.github.com&gt;; 
抄送: "Rillbeye"<532685776@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dylech30th/Pixeval] 双击应用什么反应都没有，必要的组件也都下了，之前从来没出现过这种情况，请问dalao如何解决(win10 (#121)





 
我重启电脑解决
