### ISSUE TITLE
这个BUG有点猛，还有没有一键重试下载

### ISSUE THREAD

**Issue by HA-JD** [dylech30th/Pixeval#131]
[https://imgchr.com/i/sIgDpR](url)
内存爆炸

**Comment by HA-JD** [comment]
还有高级搜索失效还得去C:\Users\用户名\AppData\Local\pixeval\settings.json改设置

**Comment by dylech30th** [comment]
内存爆炸是当前版本的一个内存泄漏问题（stackpanel默认高度无限导致虚拟化失效）我会在重构后的版本里修复
