### ISSUE TITLE
请问，最新的pixeval打开后会不停提示需要更新，图片只要点击下载就会闪退如何处理

### ISSUE THREAD

**Issue by SpicesL** [dylech30th/Pixeval#137]
您好，标题是我遇到的问题，我已经安装了NET Core 3.1和C++，win10家庭版系统，没有启动任何杀毒软件，防火墙也关闭了，可能我太笨了。。实在不清楚哪里出了问题了

**Comment by BoomBoom000** [comment]
同样问题，设置里面打开了直连的，除了以上问题还有收藏，推荐，关注都刷新不出来

**Comment by dylech30th** [comment]
请问是昨天更新的3.1.0版本吗？当时睡觉前自己弄错了一点东西，请前往https://sora.ink/Pixeval下载最新版本替换你当前的版本

**Comment by dylech30th** [comment]
#134

**Comment by SpicesL** [comment]
收到！新版本没问题了，非常感谢大佬百忙中帮我解决问题，祝一切顺利！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dylech30th/Pixeval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月10日(星期三) 凌晨4:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dylech30th/Pixeval] 请问，最新的pixeval打开后会不停提示需要更新，图片只要点击下载就会闪退如何处理 (#137)





 
请问是昨天更新的3.1.0版本吗？当时睡觉前自己弄错了一点东西，请前往https://sora.ink/Pixeval下载最新版本替换你当前的版本
