### ISSUE TITLE
The program can't view full pictures

### ISSUE THREAD

**Issue by KOTOEB** [dylech30th/Pixeval#139]
Release 3.1.0 can't load any picture, only blurry preview with a progressbar.
Direct connect is turned on. I use Windows 10 Pro x64.

**Comment by dylech30th** [comment]
When do you update your app? Please download the newest version from [Release](https://github.com/dylech30th/Pixeval/releases/tag/3.1.0), or re-download it from http://47.95.218.243/Pixeval.zip

**Comment by KOTOEB** [comment]
I updated my app yesterday.
The version from releases and from http://47.95.218.243/Pixeval.zip is not starting at all.

**Comment by dylech30th** [comment]
that makes sense, yesterday's version got a little problem so I fixed it as soon as possible, you may have downloaded the problematic version at that time, just download it from the above links again and replace old files would work

**Comment by KOTOEB** [comment]
I deleted pixeval folder from C:\Users\Admin\AppData\Local and now version from http://47.95.218.243/Pixeval.zip working good, thank you very much!
