### ISSUE TITLE
新版本打不开应该怎么调整

### ISSUE THREAD

**Issue by 1402701217** [dylech30th/Pixeval#142]
更新之后打开会提示object reference not set to an instance of an object，进不到软件里，请问应该怎么解决呢？

**Comment by dylech30th** [comment]
确定是3.1.1版本？

**Comment by dylech30th** [comment]
怎么提示的啊

**Comment by 1402701217** [comment]
是3.1.1版本，就在账号密码那个界面，有一个提示框写得object reference not set to an instance of an object，点击之后就直接退出了，进不去软件

**Comment by 1402701217** [comment]
![QQ截图20210311133902](https://user-images.githubusercontent.com/76500611/110741153-2c3b5a00-826f-11eb-9c0a-79a364f544f6.png)

**Comment by dylech30th** [comment]
你试试清理掉%localappdata%/pixeval文件夹试试

**Comment by 1402701217** [comment]
请问是在那个位置呢？

**Comment by dylech30th** [comment]
win+r输入%localappdata%/pixeval回车

**Comment by 1402701217** [comment]
可以了，非常感谢
