### ISSUE TITLE
最近突然出现这种情况怎么办

### ISSUE THREAD

**Issue by tiannailingyin** [dylech30th/Pixeval#161]
![QQ图片20210508105422](https://user-images.githubusercontent.com/59087989/117523596-d6bfc700-afeb-11eb-9b55-335948107bfe.png)
最近一直这样进不去

**Comment by Summpot** [comment]
安装webview2

**Comment by Summpot** [comment]
https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by tiannailingyin** [comment]
> 安装webview2了吗？

安装了，直到一周前都还可以正常使用

**Comment by tiannailingyin** [comment]
> 安装webview2了吗？

重新安装后问题解决了，感谢
