### ISSUE TITLE
请问后期可否可以显示作品的标签？

### ISSUE THREAD

**Issue by Jack6811** [dylech30th/Pixeval#65]
请问后期可否可以显示作品的标签？

**Comment by Rinacm** [comment]
有啊，你点开作品左下角就可以查看

**Comment by Jack6811** [comment]
可是我的软件它显示不出来啊，
![360截图20200530153904811](https://user-images.githubusercontent.com/57797431/83322619-c3f52c00-a28b-11ea-8ec9-3b55fd807c2a.jpg)

**Comment by Rinacm** [comment]
emmm...你这个是不是窗口太矮了...

**Comment by Jack6811** [comment]
那就是作者的分辨率兼容问题了。我的电脑（1920*1080）它一定会有显示不全的地方，主界面没有问题，但是大图部分作者貌似就没改过。我说怎么感觉怪怪的，可以帮我通知一下作者吗？

**Comment by Jack6811** [comment]
@Rinacm 可不可以再改改分辨率适配，感觉它还是怪怪的

**Comment by Rinacm** [comment]
好的，我过段时间改一下，这段时间作业太多
