### ISSUE TITLE
人机验证

### ISSUE THREAD

**Issue by Jack6811** [dylech30th/Pixeval#72]
**，我今天被人机验证快折磨疯了，人机验证好不容易过完了软件还是登不上去，它让重新输入账户密码，然后就是WebAPI响应超时登不上去啊，疯了疯了

**Comment by Jack6811** [comment]
然后就没有然后了，它就没了无法访问网络了，只能重启软件。从此循环

**Comment by Rinacm** [comment]
我这几天刚刚忙完，在修bug，你可以先用着旧版本
