### ISSUE TITLE
提示密码错误

### ISSUE THREAD

**Issue by saojikao** [dylech30th/Pixeval#74]
已经确认过很多次并且通过人机验证但是依然提示账号或密码错误

**Comment by Rinacm** [comment]
你是不是用中文输入法了，登陆的时候

**Comment by Jack6811** [comment]
@Rinacm 我的也是这样，之前的issues就是这个意思。你如果有时间的话就尽快更新吧。这个版本的bug不少

**Comment by Rinacm** [comment]
> @Rinacm 我的也是这样，之前的issues就是这个意思。你如果有时间的话就尽快更新吧。这个版本的bug不少

你先确认一下是不是开了中文输入法导致的

**Comment by Jack6811** [comment]
> > @Rinacm This is what I did. The previous issues meant that. If you have time, please update it as soon as possible. This version of bug is quite a few.
> 
> First you confirm whether you have opened the Chinese input method.

我现在是连更新个人资料都进不去，加载了十几分钟还在转。且任务管理器强行停止后，软件判断实例仍在运行。

**Comment by Rinacm** [comment]
> 
> > > @Rinacm This is what I did. The previous issues meant that. If you have time, please update it as soon as possible. This version of bug is quite a few.
> > 
> > First you confirm whether you have opened the Chinese input method.
> 
> 我现在是连更新个人资料都进不去，加载了十几分钟还在转。且任务管理器强行停止后，软件判断实例仍在运行。

I'll fix it as soon as I finish my exam.
之前没法修是因为期末考接近，这两天考完就会着手修

**Comment by wosanman** [comment]
> > > > @Rinacm这就是我所做的。先前的问题就意味着这一点。如果您有时间，请尽快进行更新。这个版本的bug相当多。
> > > 
> > > 
> > > 首先，请确认您是否已打开中文输入法。
> > 
> > 
> > 我现在是连更新个人资料都进不去，加载了几分钟还在转。并且任务管理器强行停止后，软件判断实例仍在运行。
> 
> 在
> 没法修是因为期末考接近，这两天考完就会着手修之前，我会尽快修复它。
请问现在问题已经修复了吗？我这个版本还是密码错误

**Comment by dylech30th** [comment]
前往https://sora.ink/archives/391上面的提示更新到最新版本试试？(3.0.2)，这个版本我没有见到过有人提交这个bug，github没有放release是因为代码和UI框架在重构
