### ISSUE TITLE
看图时的一点点建议

### ISSUE THREAD

**Issue by q4q3q9q9** [dylech30th/Pixeval#76]
1：建议加入键盘操作，比如PgDown，PgUp快速翻页，esc返回，左右键切换图片，空格键下一张图等等，能提高浏览效率（不然冲不起来啊）
2：建议设置收藏夹每次加载上限，并增加跳页功能，我收藏夹打开打着打着就卡死了（最近两个版本时都有这个bug），进度条变成了一个小点，想看以前的图很不方便......

**Comment by Rinacm** [comment]
好的，放暑假之后我会看看的
