### ISSUE TITLE
关于首页搜索功能

### ISSUE THREAD

**Issue by M1sakaaa** [dylech30th/Pixeval#83]
我直接搜索了标签名（比如arknights或者プリンセスコネクト!Re:Dive），尝试了三种不同的搜索匹配模式，并在设置中勾选了按收藏数排序，但是并没有搜索出最热门的一些图片（比如我之前自己点了收藏的一些收藏数好几k的，并带有本次搜索标签名的热门图片，）。请问大佬这种情况能优化吗。

**Comment by Rinacm** [comment]
第一，使用api最多搜索5000张，这个是P站官方API限制的上限，不能再多了，第二，当前版本热度排序有点小bug，之后会修复
