### ISSUE TITLE
最近这段时间过去之后会尽快更新的

### ISSUE THREAD

**Issue by dylech30th** [dylech30th/Pixeval#87]
这段时间家里出了大事，由于精神和物质上的双重压力，暂时没有任何更新，实际上大部分issue中所提到的bug我已经修复，只是近期没有精力整合新版本，在事情过去之后我会尽快发布更新的，感谢支持

**Comment by Iriasu** [comment]
DC加油

**Comment by Jack6811** [comment]
加油
