### ISSUE TITLE
希望能加一个队列下载,同时下载太多下载出现错误.

### ISSUE THREAD

**Issue by NLE3471** [dylech30th/Pixeval#91]
下载页面图片的时候数量很多,下载完成后有些图片只有一部分显示,文件大小也只有几十Kb,应该是没下载完整.能不能加一个队列下载,限制同时下载的文件数量.

另外图片大图模式能不能加一个下载呢,现在大图模式右键只有复制选项,只能点进画师里面去找图片来下载.

大图模式只有图片显示范围可以用点击切换图片,有些图片很小的时候比较难受,要是大图模式窗口里面点击也有效果的话就好很多了

**Comment by Rinacm** [comment]
大图模式右下角就可以下载啊，窗口点击这个我会看看，下载列表的话，其实本来是依靠.NET线程池自己的调度来处理的...不过看起来不太行，之后加个阻塞队列好了

**Comment by NLE3471** [comment]
感谢回复.大图模式下载原来在下面,我之前因为默认窗口太窄导致下面一排都没有显示,后来窗口拉开发现了.
