### ISSUE TITLE
WebApi登陆请求超时，请教一下怎么解决

### ISSUE THREAD

**Issue by i-am-devilman** [dylech30th/Pixeval#93]

**Comment by Rinacm** [comment]
see #87 ，我过段时间会针对这堆issue中的大部分bug发布更新，但是这段时间我得休息一下

**Comment by i-am-devilman** [comment]
好的大佬辛苦了

**Comment by i-am-devilman** [comment]
请教大佬我下载了最新版依旧登录不上，还是WebApi登陆请求超时

**Comment by Rinacm** [comment]
是这样的，对于一些人的网络环境来说webapi所使用的代理无法使用，会失败，可能是recatpcha的问题，也可能是网络环境的问题
我准备去除对于Windows 7的支持，这样可以使用Win10最新支持的一些框架，这样也许可以在一定程度上减少这类网络情况欠佳的人群无法登陆的问题，目前可以先用着旧版本(主要难以推进是因为保留了对Windows 7的支持，兼容做的太麻烦了)

**Comment by i-am-devilman** [comment]
原来如此，我把代理给关了现在能登上了

**Comment by Rinacm** [comment]
这情况还真是没遇见过...可能代理跟cefsharp起了冲突也说不定
